
server.port: 7008
server.error.include-message: always


logging:
level:
root: INFO
se.magnus: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_security?useSSL=false&serverTimeZone=UTC&useLegacyDatetimeCode=false
    username: root
    password: Cristian021*
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initializationFailTimeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: security-service
    security:
      jwt:
        secret-key: 586E3272357538782F413F4428472B4B6250655368566B597033733676397924
        expiration: 86400000 # un dia
        refresh-token:
          expiration: 604800000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
      instance:
      leaseRenewalIntervalInSeconds: 5
      leaseExpirationDurationInSeconds: 5
